# Change these first
owner: hari64 # Your GitHub organization or username, where this repository lives
repo: inflancer-uptime # The name of this repository

sites:
  - name: Surugara
    url: https://admin.surugara.com/ 
    check: status-code
  
  - name: TournaOP
    url: https://tournaop.com/
    check: status-code
    
  - name: Juttastudio-Admin
    url: https://admin.juttastudio.com/
    check: status-code
    
  - name: Juttastudio
    url: https://juttastudio.com/
    check: status-code
  - name: Juttastudio Admin
    url: https://admin.juttastudio.com/
    check: status-code
    
  - name: Ekjhola
    url: https://ekjhola.com/
    check: status-code
   
  - name: The Job Room
    url: https://thejobroom.com/
    check: status-code 
    
  
  - name: Khana247-Admin
    url: https://admin.khana247.com/admin/auth/login
    check: status-code 
  - name: Khana247
    url: https://khana247.com
    check: status-code
    
  - name: Thyakkai
    url: https://thyakkai.com/
    check: status-code 
    
  - name: Bechideu
    url: https://bechideu.com/
    check: status-code
  - name: Bechideu Blog
    url: https://blogs.bechideu.com/
    check: status-code
    
  - name: Ohmnom
    url: https://ohmnom.com/
    check: status-code 
    
  - name: Machamasu
    url: https://machamasu.dhanapati.com/admin
    check: status-code 
    
  - name: Lagaani Store
    url: https://admin.lagaanistore.com/
    check: status-code 
    
  - name: Surugara
    url: https://admin.surugara.com/
    check: status-code 
    
  - name: Dhanapati
    url: https://dhanapati.com/
    check: status-code 
    
  - name: Upit Studio
    url: https://upit.dhanapati.com/
    check: status-code 
    
  - name: Sodhpuch
    url: https://beta.sodhpuch.com/
    check: status-code 
    
  - name: Mero Degree
    url: https://merodegree.com/
    check: status-code 
    
  - name: Share a Book Nepal  
    url: https://shareabooknepal.com/
    check: status-code 
    
  - name: Bhansa
    url: https://bhaansa.com/
    check: status-code 
  - name: Bhansa Admin
    url: https://admin.bhaansa.com/
    check: status-code

  - name: Gharsuvida Admin
    url: https://admin.gharsuvida.com/
    check: status-code
  - name: Gharsuvida
    url: https://admin.gharsuvida.com/
    check: status-code
  
  - name: Bhansa Admin
    url: https://admin.bhaansa.com/
    check: status-code
    
  - name: imart
    url: https://imart.inflancer.com/
    check: status-code 
    
  - name: Imart Admin
    url: https://imart-admin.inflancer.com/
    check: status-code
    
  - name: Phisss
    url: https://admin.phisss.com/
    check: status-code 
    
  - name: Rentgara  
    url: https://rentgara.dhanapati.com/
    check: status-code 
    
  - name: Prabhusteel
    url: https://prabhusteel.com/
    check: status-code

  - name: Holdings Hydro
    url: https://holdingshydro.com/
    check: status-code

  - name: Prabhu Cable Car Admin
    url: https://admin.bhaansa.com/
    check: status-code

  - name: Prabhu Holdings
    url: https://holdingsprabhu.com/
    check: status-code
    
  - name: Specsy-Admin
    url: https://admin.specsy.app/
    check: status-code
    
  # - name: Specsy-Api
  #   url: https://api.specsy.app/
  #   check: status-code
  
  - name: Pre-school Krishna Sah
    url: https://preschool.krishna-sah.com.np/
    check: status-code
    
  - name: Inflancer
    url: https://inflancer.com/
    check: status-code
    
  # - name: Merobazar-Admin
  #   url: https://madmin.inflancer.tech/
  #   check: status-code

  - name: Mapasey Admin
    url: https://admin.mapasey.com/
    check: status-code
  - name: Mapasey
    url: https://mapasey.com/
    check: status-code

  - name: Aesthetix
    url: https://aesthetix.inflancer.com/
    check: status-code

  - name: Inflancer App
    url: https://app.inflnacer.com/
    check: status-code

  

    
status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /inflancer-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Inflancer Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
